### ISSUE TITLE
TableRow not working properly

### ISSUE THREAD

**Issue by pavlos2094** [dmk99/react-pdf-table#1]
Hi, thanks for your repo. I am trying to create a table with multiple rows but the TableRow Component doesn't seem to work properly. Below code: 

`<TableBody>

    <TableRow>
        <DataTableCell weighting={0.3} getContent={() => 'First'}/>
        <DataTableCell weighting={0.3} getContent={() => 'First'}/>
        <DataTableCell getContent={() => 'First'}/>
        <DataTableCell getContent={() => 'First'}/>
        <DataTableCell getContent={() => 'First'}/>
    </TableRow>
    <TableRow>
        <DataTableCell weighting={0.3} getContent={() => 'First'}/>
        <DataTableCell weighting={0.3} getContent={() => 'First'}/>
        <DataTableCell getContent={() => 'First'}/>
        <DataTableCell getContent={() => 'First'}/>
        <DataTableCell getContent={() => 'First'}/>
    </TableRow>
</TableBody>`

renders this result: 

![image](https://user-images.githubusercontent.com/37660370/60441896-9e494800-9c20-11e9-8780-7f2ba10b5a80.png)

that is, both rows one on top of the other instead of below. Any help? Thanks!

**Comment by dmk99** [comment]
Hi,

This is not entirely clear, I will update the documentation to be a bit clearer. 

You should only supply one `TableRow` (and/or one `TableHeader`) into a table and use the `data` in the `Table` object to drive the number of rows to display.

So with using your example from above it should look like:
```
                <Table
                    data={[0, 0]}
                >
                    <TableHeader>
                        <TableCell weighting={0.3}>
                            First Name
                        </TableCell>
                        <TableCell weighting={0.3}>
                            Last Name
                        </TableCell>
                        <TableCell>
                            DOB
                        </TableCell>
                        <TableCell>
                            Country
                        </TableCell>
                        <TableCell>
                            Phone Number
                        </TableCell>
                    </TableHeader>
                    <TableBody>
                        <DataTableCell weighting={0.3} getContent={() => 'First'}/>
                        <DataTableCell weighting={0.3} getContent={() => 'First'}/>
                        <DataTableCell getContent={() => 'First'}/>
                        <DataTableCell getContent={() => 'First'}/>
                        <DataTableCell getContent={() => 'First'}/>
                    </TableBody>
                </Table>
```

Where `data` is two "rows".
You should then get something like:
![image](https://user-images.githubusercontent.com/426483/60474469-c11d4000-9ca4-11e9-9d8c-175b0086c5dd.png)

Hopefully this helps!

**Comment by dmk99** [comment]
Just as a follow on from my previous comment, `TableRow` shouldn't be used directly it's an internal component which I shouldn't be exporting out. `TableBody` and `TableHeader` use `TableRow` internally to generate the row container.

**Comment by pavlos2094** [comment]
I see, works like a charm now! Thanks.
