### ISSUE TITLE
Question: Is there a was to repeat table header if the table is displayed on more than one page?

### ISSUE THREAD

**Issue by eightshone** [dmk99/react-pdf-table#11]
I have the case where a table is split on multiple pages and I couldn't find a way to repeat the header on the needed pages.

**Comment by dmk99** [comment]
Right now there is no built-in ability to do that. On a project that I use this for I will usually batch up the rows into a number of pages and then create a function to create the tables in a loop on the separate pages. I generally find `24` rows per page to be a good number, it allows me the ability to have headers and footers on the page as well.

Getting table pagination working nicely is a bit tricky. If there are any suggestions on how it could be achieved I'd be happy to hear it!

**Comment by eightshone** [comment]
I see, I’ll figure a way out.
