### ISSUE TITLE
getContent   How do I support Dom rendering

### ISSUE THREAD

**Issue by leishihong** [dmk99/react-pdf-table#13]
![image](https://user-images.githubusercontent.com/26375364/75309204-518b3f00-588b-11ea-969d-b90f3fd58a9f.png)

**Comment by dmk99** [comment]
Hi, unfortunately you can't use DOM components. If you want a custom display you need to utilise the react-pdf components e.g. `View`, `Text`, `Image` etc. You would then apply a custom style to these elements to get the required look and feel.

More information on the components here: https://react-pdf.org/components

Regarding your example above you could use:

```
getContent={r => {
   return <View><Text>{r.lastName}</Text></View>
})
```
