### ISSUE TITLE
表格的样式能美化吗，我想要这种效果的，但是修改了好长时间都不好使

### ISSUE THREAD

**Issue by leishihong** [dmk99/react-pdf-table#16]
![image](https://user-images.githubusercontent.com/26375364/76754268-ca135a80-67bc-11ea-9dc4-d9abf909cc03.png)

**Comment by dmk99** [comment]
I'm sure it's quite possible to style a table like this. You should be able to modify the `style` properties passed to the components but you also need to remember that you won't have the full CSS styling capabilities because react-pdf may not use those CSS styles.
