### ISSUE TITLE
TableHeader not rendering on the next page

### ISSUE THREAD

**Issue by muriwai-cd** [dmk99/react-pdf-table#20]
Is there a way of rendering the TableHeader on the following pages

**Comment by dmk99** [comment]
Unfortunately table headers are not carried across pages. The way that i recommend handling this scenario is to determine how many rows generally appear on a page and then batch up the rows. I've personally found for a landscape page that it can fit around 20-30 rows using the default styling.

Then render a new page (with a table) for each batch.
