### ISSUE TITLE
How show non-latin data?

### ISSUE THREAD

**Issue by DFilyushin** [dmk99/react-pdf-table#25]
import {
    Table,
    TableCell,
    TableHeader,
    TableBody,
    DataTableCell
} from '@david.kucsai/react-pdf-table'

For react-pdf added font register:
Font.register({ family: 'Arial', src: '/fonts/Arial-Regular.ttf' });
Font.register({ family: 'Arial-Bold', src: '/fonts/Arial-Bold.ttf' });

<Table data={[
                            {seller: 'Поставщик', customer: 'Покупатель'}
                        ]}>
                            <TableHeader>
                                <TableCell>
                                    Поставщик
                                </TableCell>
                                <TableCell>
                                    Покупатель
                                </TableCell>
                            </TableHeader>
                            <TableBody>
                                <DataTableCell getContent={(r) => r.seller}/>
                                <DataTableCell getContent={(r) => r.customer}/>
                            </TableBody>
                        </Table>

![screen](https://user-images.githubusercontent.com/5266873/89749289-40f51b00-daf1-11ea-869d-b01113e3b911.png)

**Comment by dmk99** [comment]
Hi,

Unfortunately I have not tested this with non latin fonts. Thank you for bringing it to my attention.
I will investigate how we can best support it.

**Comment by dmk99** [comment]
If this is still relevant to you, this can actually be achieved by setting up the style for the `DataTableCell`.
Below is an example that will work with your text:

```
import {useState} from "react";
import {PdfContainer} from "../PdfContainer";
import * as React from "react";
import {DataTableCell, Table, TableBody, TableCell, TableHeader} from "../../../src";
import {Font, Text} from "@react-pdf/renderer";

const Roboto = require("../../resources/Roboto-Regular.ttf");
const RobotoBold = require("../../resources/Roboto-Bold.ttf");

export default () => {
    const [items, setItems] = useState<string[]>([
        "Поставщик Покупатель",
        "γεια"
    ]);

    Font.register({
        family: 'Roboto', fonts: [
            {src: Roboto},
            {src: RobotoBold, fontWeight: "bold"}
        ]
    });

    return (
        <PdfContainer>
            <Table
                data={items}
            >
                <TableHeader>
                    <TableCell>Text</TableCell>
                </TableHeader>
                <TableBody>
                    <DataTableCell getContent={c => <Text style={{fontFamily: "Roboto"}}>{c}</Text>} />
                </TableBody>
            </Table>
        </PdfContainer>
    )
}
```

Note that I am setting the `fontFamily` here:
`<DataTableCell getContent={c => <Text style={{fontFamily: "Roboto"}}>{c}</Text>} />`

If you set yours to `Arial` then it should work.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/426483/94895046-2a4dbd80-04bd-11eb-8597-d006667c5d41.png">
