### ISSUE TITLE
IE 11 compatibility

### ISSUE THREAD

**Issue by gmmurugan** [dmk99/react-pdf-table#3]
couldnt render the storybook itself in IE11

**Comment by dmk99** [comment]
Thanks for reporting this issue. I generally develop on a Mac so I haven't tested this with Internet Explorer. The error in the console when loading the Storybook appears to be:

![image](https://user-images.githubusercontent.com/426483/62828417-7d5d1500-bc18-11e9-901d-a31577888bb2.png)

Looks to be related to this issue: https://github.com/storybookjs/storybook/issues/7263#issuecomment-518925433

**Comment by dmk99** [comment]
This is partially fixed in version 0.1.1. The storybook will now display but the actual Table stories are failing to render because a script is taking too long to run. I will be watching the storybook github to see if there are any resolutions.

**Comment by dmk99** [comment]
Storybook has been updated. Closing out this issue as IE11 is a known issue.
