### ISSUE TITLE
How to run this alongside react-pdf

### ISSUE THREAD

**Issue by jamesshapiro** [dmk99/react-pdf-table#30]
Suppose that you run 

```bash
git clone https://github.com/diegomura/react-pdf.git
cd react-pdf
npm install "@david.kucsai/react-pdf-table"
```

How would you then go about importing the Table and related components into your project? Is this even possible / the intended way of using it?

**Comment by isuhendro** [comment]
Maybe this issue will help https://github.com/dmk99/react-pdf-table/issues/21
