### ISSUE TITLE
How to merge cell 

### ISSUE THREAD

**Issue by tuanhai2712** [dmk99/react-pdf-table#36]
I want to make Table like this. How can I do it ????
![Capture](https://user-images.githubusercontent.com/35209688/115368217-149dac80-a1f1-11eb-8c10-d5e525089c6a.PNG)

**Comment by dmk99** [comment]
Unfortunately the library was not created with the explicit ability to merge cells but you should be able to achieve something similar by taking a look at the nested tables example.

Direct link: https://dmk99.github.io/react-pdf-table/iframe.html?id=table--nested-tables

the code can be found here: https://github.com/dmk99/react-pdf-table/blob/master/stories/components/story/NestedTables.tsx

To get the columns with different widths refer to the weighting example in the readme.

Hopefully this helps.
