### ISSUE TITLE
styling rows

### ISSUE THREAD

**Issue by leandrovegacr** [dmk99/react-pdf-table#37]
Hi, thanks for your work.

I've been fiddling with the library today, and was trying to zebra-color rows in my table, but I've not found how to do it... I use DataTableCells to display info, and even if I can style each row, I can't seem to find a way to style it depending if it is even or odd.

I was thinking it could be useful the DataTableCell component can have access to each row not only to get content to display, but to get the styling also, which would make the styling more powerful. Don't know if you have came accross something like this, and if you have thought about a way to solve it.

Thanks again, I could also try to help with this, if the project is accepting collaborations.

I paste a sample of what I need:

![image](https://user-images.githubusercontent.com/26399272/118038612-94202680-b32c-11eb-83ea-791e0fa0abb9.png)

**Comment by joao-fb** [comment]
I would love hear about this as well!

**Comment by dmk99** [comment]
Great idea. This will be something to explore.

**Comment by nathanpdaniel** [comment]
I created #42 to enable this.

**Comment by dmk99** [comment]
Merged in #42 by @nathanpdaniel. Version 0.4.0 will have this functionality.
