### ISSUE TITLE
Can we achieve two tables side by sides in a single render 

### ISSUE THREAD

**Issue by sr2399** [dmk99/react-pdf-table#39]
Hi 
I want to achieve side by side in a single page and also the data should start where its ending on the left table.
i.e. I want data continuing from the end of the left table

**Comment by dmk99** [comment]
In theory you should be able to achieve this, you would just need to use the react-pdf/renderer `View` components with a style taking 50% of the screen. You could then split up your table data in half and create two  `Table`s.

This is just an example of what it could look like, I have not tested this:

```
<PDFViewer>
    <Document>
        <Page>
            <View>
                <Table data={firstHalfArray}>
                </Table>
            </View>
            <View>
                <Table data={secondHalfArray}>
                </Table>
            </View>
        </Page>
    <Document>
</PDFViewer>
```
