### ISSUE TITLE
Add it to React-Pdf

### ISSUE THREAD

**Issue by Misiu** [dmk99/react-pdf-table#4]
Hi there,
Did You consider adding it to `react-pdf`?
This would help a lot because many users are looking for tables support.

BTW awesome work 😁

**Comment by dmk99** [comment]
Hi Misiu,

Yes, I have considered it for sure. Atm there's a few changes/features I want to add to it before I'd feel comfortable getting it integrated into react-pdf. It also depends on whether the way tables are defined in this project matches the overall vision for react-pdf.

Thanks for the kind words.

David
