### ISSUE TITLE
when i intall react-pdf-table it ask host key verification

### ISSUE THREAD

**Issue by MeginMelkias** [dmk99/react-pdf-table#5]
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.

**Comment by dmk99** [comment]
Can you please tell me what command you are running that causes this error?

**Comment by MeginMelkias** [comment]
Actually, I am new to React and NodeJs. The problem is I try  **npm install @david.kucsai/react-pdf-table**  in  Windows PowerShell is thrown an error.
 After I change the commend as  **npm install "@david.kucsai/react-pdf-table"** .Now the installation is working fine.

**Comment by khuramdogar** [comment]
can't install either 
npm error Cannot read properties of null (reading 'matches')
