### ISSUE TITLE
Styling?

### ISSUE THREAD

**Issue by coconewty** [dmk99/react-pdf-table#8]
Hey, thanks for this, I like the syntax, good work :)

I can't work out how to style the components though? I've tried composing with styled components...

```
import styled from '@react-pdf/styled-components'
import { Table as TableOrig } from '@david.kucsai/react-pdf-table'
const Table = styled(TableOrig)`/* stuff */`
```

... and also regular ...

`<Table style={{ foo: 'bar' }}>`

... and none of this seems to work. Am I doing something dumb?

**Comment by Trym-H** [comment]
Based on issue#9 here on GitHub (quoted below), you need to use **styles={{ foo: 'bar' }}** instead of **style**

> I got hung up on trying to use "style" property like we do with react-pdf components, but in react-pdf-table components you need to use "styles".
> 
> Is this intentional to use `styles` rather than `style`?
> 
> If possible it seems like it would be better to match react-pdf.
> 
> So currently this works
> 
> ```js-jsx
> <TableCell styles={styles.headerCell}>Week Start</TableCell>
> ```
> 
> but I'm thinking it would be better to match react-pdf so it's not as confusing when switching between them and not realizing why it isn't working.
> 
> ```js-jsx
> <TableCell style={styles.headerCell}>Week Start</TableCell>
> ```
> 
> https://react-pdf.org/styling

**Comment by dmk99** [comment]
Thanks for bringing this up. As stated #9 will be where this update is taking place.
